Repository Kernel360/KBE5-Rento-BE, pull requests merged in 2025-06, with the labels that each got.

#55 [BE] refactor: event패키지 분리 + onEvent 기능 수정
  src/main/java/com/kbe5/rento/common/jwt/util/JwtFilter.java
  src/main/java/com/kbe5/rento/domain/device/controller/DeviceController.java
  src/main/java/com/kbe5/rento/domain/device/controller/DeviceControllerImpl.java
  src/main/java/com/kbe5/rento/domain/device/dto/resonse/DeviceTokenResponse.java
  src/main/java/com/kbe5/rento/domain/device/dto/resonse/OnEventResponse.java
  src/main/java/com/kbe5/rento/domain/device/entity/DeviceToken.java
  src/main/java/com/kbe5/rento/domain/device/entity/event/OnOffEvent.java
  src/main/java/com/kbe5/rento/domain/device/repository/DeviceEventRepository.java
  src/main/java/com/kbe5/rento/domain/device/service/DeviceEventService.java
  src/main/java/com/kbe5/rento/domain/event/controller/OnOffController.java
  src/main/java/com/kbe5/rento/domain/event/controller/OnOffControllerImpl.java
  src/main/java/com/kbe5/rento/domain/event/dto/request/onoff/OnEventRequest.java
  src/main/java/com/kbe5/rento/domain/event/dto/response/onoff/OnEventResponse.java
  src/main/java/com/kbe5/rento/domain/event/entity/Event.java
  src/main/java/com/kbe5/rento/domain/event/entity/OnOffEvent.java
  src/main/java/com/kbe5/rento/domain/event/repository/EventRepository.java
  src/main/java/com/kbe5/rento/domain/event/service/OnOffEventService.java
  src/main/resources/application-local.yml
  src/test/java/com/kbe5/rento/domain/device/service/DeviceEventServiceTest.java
  src/test/java/com/kbe5/rento/domain/event/dto/request/OnEventRequestTest.java
  src/test/java/com/kbe5/rento/domain/event/service/OnOffEventServiceTest.java
Labels: ⭐개발, 🔧리팩토링

#57 [BE] 차량 구조 변경 및 테스트 코드 기본 베이스 구성
  build.gradle
  src/main/java/com/kbe5/rento/domain/drive/controller/DriveController.java
  src/main/java/com/kbe5/rento/domain/drive/controller/DriveControllerImpl.java
  src/main/java/com/kbe5/rento/domain/drive/dto/DriveResponse.java
  src/main/java/com/kbe5/rento/domain/drive/entity/Drive.java
  src/main/java/com/kbe5/rento/domain/drive/service/DriveService.java
  src/main/java/com/kbe5/rento/domain/manager/entity/Manager.java
  src/main/java/com/kbe5/rento/domain/vehicle/controller/VehicleController.java
  src/main/java/com/kbe5/rento/domain/vehicle/controller/VehicleControllerImpl.java
  src/main/java/com/kbe5/rento/domain/vehicle/dto/request/VehicleAddRequest.java
  src/main/java/com/kbe5/rento/domain/vehicle/dto/request/VehicleUpdateRequest.java
  src/main/java/com/kbe5/rento/domain/vehicle/dto/response/VehicleDetailResponse.java
  src/main/java/com/kbe5/rento/domain/vehicle/dto/response/VehicleResponse.java
  src/main/java/com/kbe5/rento/domain/vehicle/entity/Vehicle.java
  src/main/java/com/kbe5/rento/domain/vehicle/entity/VehicleInfo.java
  src/main/java/com/kbe5/rento/domain/vehicle/entity/VehicleMilleage.java
  src/main/java/com/kbe5/rento/domain/vehicle/repository/VehicleRepository.java
  src/main/java/com/kbe5/rento/domain/vehicle/service/VehicleService.java
  src/test/java/com/kbe5/rento/domain/drive/service/DriveServiceTest.java
  src/test/java/com/kbe5/rento/domain/vehicle/service/VehicleServiceTest.java
  src/testFixtures/java/com/kbe5/rento/CompanyTestFixtures.java
  src/testFixtures/java/com/kbe5/rento/DepartmentTestFixtures.java
  src/testFixtures/java/com/kbe5/rento/DriveTestFixtures.java
  src/testFixtures/java/com/kbe5/rento/ManagerTestFixtures.java
  src/testFixtures/java/com/kbe5/rento/MemberTestFixtures.java
  src/testFixtures/java/com/kbe5/rento/VehicleTestFixtures.java
Labels: ⭐개발

#80 [BE] bulk insert 기능 구현
  build.gradle
  src/main/java/com/kbe5/rento/domain/event/dto/request/cycleinfo/CycleInfoRequest.java
  src/main/java/com/kbe5/rento/domain/event/entity/CycleInfo.java
  src/main/java/com/kbe5/rento/domain/event/repository/CycleInfoJdbcRepository.java
  src/main/java/com/kbe5/rento/domain/event/repository/CycleInfoJdbcRepositoryImpl.java
  src/main/java/com/kbe5/rento/domain/event/repository/CycleInfoRepository.java
  src/main/java/com/kbe5/rento/domain/event/service/CycleInfoService.java
  src/main/resources/application-local.yml
  src/test/java/com/kbe5/rento/domain/event/dto/request/OnEventRequestTest.java
Labels: ⭐개발

#82 [BE] 사용자 등록 및 업데이트 시 중복 값 체크 변경
  src/main/java/com/kbe5/rento/common/exception/ErrorType.java
  src/main/java/com/kbe5/rento/common/util/SecurityPermissionApiList.java
  src/main/java/com/kbe5/rento/domain/member/controller/MemberControllerImpl.java
  src/main/java/com/kbe5/rento/domain/member/repository/MemberRepository.java
  src/main/java/com/kbe5/rento/domain/member/service/MemberService.java
  src/test/java/com/kbe5/rento/domain/member/service/MemberServiceTest.java
Labels: 🐛 버그, 👩🏻‍💼 사용자

#103 [BE] rabbitmq 구현 + handler
  build.gradle
  src/main/java/com/kbe5/rento/common/config/RabbitConfig.java
  src/main/java/com/kbe5/rento/common/config/SecurityConfig.java
  src/main/java/com/kbe5/rento/common/util/SecurityPermissionApiList.java
  src/main/java/com/kbe5/rento/domain/device/enums/EventType.java
  src/main/java/com/kbe5/rento/domain/event/amqp/EventReceiver.java
  src/main/java/com/kbe5/rento/domain/event/amqp/EventSender.java
  src/main/java/com/kbe5/rento/domain/event/controller/CycleInfoControllerImpl.java
  src/main/java/com/kbe5/rento/domain/event/controller/EventController.java
  src/main/java/com/kbe5/rento/domain/event/controller/GeofenceEventControllerImpl.java
  src/main/java/com/kbe5/rento/domain/event/controller/OnOffController.java
  src/main/java/com/kbe5/rento/domain/event/controller/OnOffControllerImpl.java
  src/main/java/com/kbe5/rento/domain/event/dto/request/cycleinfo/CycleEventRequest.java
  src/main/java/com/kbe5/rento/domain/event/dto/request/onoff/OffEventRequest.java
  src/main/java/com/kbe5/rento/domain/event/dto/request/onoff/OnEventRequest.java
  src/main/java/com/kbe5/rento/domain/event/dto/response/EventResponse.java
  src/main/java/com/kbe5/rento/domain/event/entity/CycleEvent.java
  src/main/java/com/kbe5/rento/domain/event/entity/Event.java
  src/main/java/com/kbe5/rento/domain/event/entity/OnOffEvent.java
  src/main/java/com/kbe5/rento/domain/event/enums/EventType.java
  src/main/java/com/kbe5/rento/domain/event/service/CycleInfoHandler.java
  src/main/java/com/kbe5/rento/domain/event/service/CycleInfoService.java
  src/main/java/com/kbe5/rento/domain/event/service/EventHandler.java
  src/main/java/com/kbe5/rento/domain/event/service/EventService.java
  src/main/java/com/kbe5/rento/domain/event/service/OffEventHandler.java
  src/main/java/com/kbe5/rento/domain/event/service/OnEventHandler.java
  src/main/java/com/kbe5/rento/domain/member/controller/MemberControllerImpl.java
  src/main/resources/application.yml
Labels: ⭐개발

#115 [BE]cycle info lat and lon refactoring
  src/main/java/com/kbe5/rento/common/util/SecurityPermissionApiList.java
  src/main/java/com/kbe5/rento/domain/device/enums/GpsCondition.java
  src/main/java/com/kbe5/rento/domain/event/entity/CycleInfo.java
  src/main/resources/application-local.yml
Labels: 🐛 버그

#126 refresh token redis에서 관리하는 로직 구현
  build.gradle
  src/main/java/com/kbe5/rento/common/config/RedisConfig.java
  src/main/java/com/kbe5/rento/common/exception/ErrorType.java
  src/main/java/com/kbe5/rento/common/jwt/entity/JwtRefresh.java
  src/main/java/com/kbe5/rento/common/jwt/respository/JwtRefreshRepository.java
  src/main/java/com/kbe5/rento/common/jwt/util/JwtFilter.java
  src/main/java/com/kbe5/rento/common/jwt/util/JwtProperties.java
  src/main/java/com/kbe5/rento/common/jwt/util/JwtUtil.java
  src/main/java/com/kbe5/rento/common/response/api/ApiResponse.java
  src/main/java/com/kbe5/rento/common/response/api/ApiResultCode.java
  src/main/java/com/kbe5/rento/common/response/error/ErrorResponse.java
  src/main/java/com/kbe5/rento/common/securityFilter/LoginAuthenticationFilter.java
  src/main/java/com/kbe5/rento/domain/device/dto/resonse/GeofenceControlInfoResponse.java
  src/main/java/com/kbe5/rento/domain/device/entity/GeofenceControlInfo.java
  src/main/resources/application-deploy.yml
  src/main/resources/application-local.yml
  src/main/resources/application-test.yml
  src/test/java/com/kbe5/rento/common/apiresponse/ApiResponseTest.java
  src/test/java/com/kbe5/rento/common/util/JwtUtilTest.java
Labels: ⭐개발

#148 [BE] 멀티모듈 기준으로 리팩토링
  common/src/main/java/com/kbe5/common/exception/ErrorType.java
  common/src/main/java/com/kbe5/common/util/DateUtil.java
  common/src/main/java/com/kbe5/common/util/EventLocalDateTimeDeserializer.java
  rento-adapter/src/main/java/com/kbe5/adapter/config/EventHealthCheckController.java
  rento-adapter/src/main/java/com/kbe5/adapter/controller/EventController.java
  rento-adapter/src/main/java/com/kbe5/adapter/dto/request/cycleinfo/CycleEventRequest.java
Labels: ⭐개발

#151 [BE] @RequestHeader 를 사용해서 deviceToken 가져오도록 구현 security 제거
  rento-adapter/build.gradle
  rento-adapter/src/main/java/com/kbe5/adapter/controller/EventController.java
  rento-adapter/src/main/java/com/kbe5/adapter/service/DeviceTokenService.java
Labels: ⭐개발

#152 [BE]CycleEventRequest oTime @JsonDeserialize 추가 hotfix
  rento-adapter/src/main/java/com/kbe5/adapter/dto/request/cycleinfo/CycleEventRequest.java
  rento-adapter/src/main/java/com/kbe5/adapter/dto/request/cycleinfo/CycleInfoRequest.java
  rento-adapter/src/main/java/com/kbe5/adapter/dto/request/onoff/OffEventRequest.java
  rento-adapter/src/main/java/com/kbe5/adapter/dto/request/onoff/OnEventRequest.java
Labels: ⭐개발

#155 Jwt의 payload의 id값을 uuid로 수정
  domain/src/main/java/com/kbe5/domain/manager/entity/Manager.java
  rento-api/src/main/java/com/kbe5/api/config/RedisConfig.java
  rento-api/src/main/java/com/kbe5/api/domain/jwt/dto/JwtManagerArgumentDto.java
  rento-api/src/main/java/com/kbe5/api/domain/jwt/util/JwtUtil.java
  rento-api/src/main/java/com/kbe5/api/filter/LoginAuthenticationFilter.java
Labels: ⭐개발

#157 로그아웃 시 리프레시 삭제 구현
  common/src/main/java/com/kbe5/common/exception/ErrorType.java
  rento-api/src/main/java/com/kbe5/api/domain/jwt/util/JwtFilter.java
  rento-api/src/main/java/com/kbe5/api/domain/jwt/util/JwtUtil.java
  rento-api/src/main/java/com/kbe5/api/domain/manager/service/ManagerService.java
Labels: ⭐개발

#168 jwt payload aes256 암호화 적용
  common/src/main/java/com/kbe5/common/exception/ErrorType.java
  common/src/main/java/com/kbe5/common/util/Aes256Util.java
  rento-api/src/main/java/com/kbe5/api/config/SecurityConfig.java
  rento-api/src/main/java/com/kbe5/api/config/SecurityPermissionApiList.java
  rento-api/src/main/java/com/kbe5/api/domain/jwt/controller/JwtController.java
  rento-api/src/main/java/com/kbe5/api/domain/jwt/controller/JwtRefreshController.java
  rento-api/src/main/java/com/kbe5/api/domain/jwt/dto/request/PayloadDecryptRequest.java
  rento-api/src/main/java/com/kbe5/api/domain/jwt/dto/response/PayloadDecryptResponse.java
  rento-api/src/main/java/com/kbe5/api/domain/jwt/enums/MaskCategory.java
  rento-api/src/main/java/com/kbe5/api/domain/jwt/util/JwtFilter.java
  rento-api/src/main/java/com/kbe5/api/domain/jwt/util/JwtProperties.java
  rento-api/src/main/java/com/kbe5/api/domain/jwt/util/JwtUtil.java
  rento-api/src/main/java/com/kbe5/api/domain/manager/dto/request/ManagerLoginRequest.java
Labels: ⭐개발
